[package]
name = "skdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
rocksdb = "0.17.0"
clap = { version = "3.0.9", features = ["derive"] }