// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `diner.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct Order {
    // message fields
    pub items: ::std::vec::Vec<Item>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Order {
    fn default() -> &'a Order {
        <Order as ::protobuf::Message>::default_instance()
    }
}

impl Order {
    pub fn new() -> Order {
        ::std::default::Default::default()
    }

    // repeated .example.Item items = 1;


    pub fn get_items(&self) -> &[Item] {
        &self.items
    }
    pub fn clear_items(&mut self) {
        self.items.clear();
    }

    // Param is passed by value, moved
    pub fn set_items(&mut self, v: ::std::vec::Vec<Item>) {
        self.items = v;
    }

    // Mutable pointer to the field.
    pub fn mut_items(&mut self) -> &mut ::std::vec::Vec<Item> {
        &mut self.items
    }

    // Take field
    pub fn take_items(&mut self) -> ::std::vec::Vec<Item> {
        ::std::mem::replace(&mut self.items, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Order {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_enum_with_unknown_fields_into(wire_type, is, &mut self.items, 1, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.items {
            my_size += ::protobuf::rt::enum_size(1, *value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.items {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(v))?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Order {
        Order::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Item>>(
                "items",
                |m: &Order| { &m.items },
                |m: &mut Order| { &mut m.items },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Order>(
                "Order",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Order {
        static instance: ::protobuf::rt::LazyV2<Order> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Order::new)
    }
}

impl ::protobuf::Clear for Order {
    fn clear(&mut self) {
        self.items.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Order {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Order {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Check {
    // message fields
    pub total: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Check {
    fn default() -> &'a Check {
        <Check as ::protobuf::Message>::default_instance()
    }
}

impl Check {
    pub fn new() -> Check {
        ::std::default::Default::default()
    }

    // double total = 1;


    pub fn get_total(&self) -> f64 {
        self.total
    }
    pub fn clear_total(&mut self) {
        self.total = 0.;
    }

    // Param is passed by value, moved
    pub fn set_total(&mut self, v: f64) {
        self.total = v;
    }
}

impl ::protobuf::Message for Check {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.total = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.total != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.total != 0. {
            os.write_double(1, self.total)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Check {
        Check::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                "total",
                |m: &Check| { &m.total },
                |m: &mut Check| { &mut m.total },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Check>(
                "Check",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Check {
        static instance: ::protobuf::rt::LazyV2<Check> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Check::new)
    }
}

impl ::protobuf::Clear for Check {
    fn clear(&mut self) {
        self.total = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Check {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Check {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Item {
    SPAM = 0,
    EGGS = 1,
    HAM = 2,
}

impl ::protobuf::ProtobufEnum for Item {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Item> {
        match value {
            0 => ::std::option::Option::Some(Item::SPAM),
            1 => ::std::option::Option::Some(Item::EGGS),
            2 => ::std::option::Option::Some(Item::HAM),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Item] = &[
            Item::SPAM,
            Item::EGGS,
            Item::HAM,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<Item>("Item", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for Item {
}

impl ::std::default::Default for Item {
    fn default() -> Self {
        Item::SPAM
    }
}

impl ::protobuf::reflect::ProtobufValue for Item {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bdiner.proto\x12\x07example\",\n\x05Order\x12#\n\x05items\x18\x01\
    \x20\x03(\x0e2\r.example.ItemR\x05items\"\x1d\n\x05Check\x12\x14\n\x05to\
    tal\x18\x01\x20\x01(\x01R\x05total*#\n\x04Item\x12\x08\n\x04SPAM\x10\0\
    \x12\x08\n\x04EGGS\x10\x01\x12\x07\n\x03HAM\x10\x0220\n\x05Diner\x12'\n\
    \x03Eat\x12\x0e.example.Order\x1a\x0e.example.Check\"\0J\xaa\x03\n\x06\
    \x12\x04\0\0\x14\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\
    \x03\x02\0\x10\n\n\n\x02\x06\0\x12\x04\x04\0\x06\x01\n\n\n\x03\x06\0\x01\
    \x12\x03\x04\x08\r\n\x0b\n\x04\x06\0\x02\0\x12\x03\x05\x02#\n\x0c\n\x05\
    \x06\0\x02\0\x01\x12\x03\x05\x06\t\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\
    \x05\n\x0f\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x05\x1a\x1f\n\n\n\x02\x05\
    \0\x12\x04\x08\0\x0c\x01\n\n\n\x03\x05\0\x01\x12\x03\x08\x05\t\n\x0b\n\
    \x04\x05\0\x02\0\x12\x03\t\x02\x0b\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\t\
    \x02\x06\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\t\t\n\n\x0b\n\x04\x05\0\x02\
    \x01\x12\x03\n\x02\x0b\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\n\x02\x06\n\
    \x0c\n\x05\x05\0\x02\x01\x02\x12\x03\n\t\n\n\x0b\n\x04\x05\0\x02\x02\x12\
    \x03\x0b\x02\n\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\x0b\x02\x05\n\x0c\n\
    \x05\x05\0\x02\x02\x02\x12\x03\x0b\x08\t\n\n\n\x02\x04\0\x12\x04\x0e\0\
    \x10\x01\n\n\n\x03\x04\0\x01\x12\x03\x0e\x08\r\n\x0b\n\x04\x04\0\x02\0\
    \x12\x03\x0f\x02\x1a\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x0f\x02\n\n\x0c\
    \n\x05\x04\0\x02\0\x06\x12\x03\x0f\x0b\x0f\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03\x0f\x10\x15\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0f\x18\x19\n\n\
    \n\x02\x04\x01\x12\x04\x12\0\x14\x01\n\n\n\x03\x04\x01\x01\x12\x03\x12\
    \x08\r\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x13\x02\x13\n\x0c\n\x05\x04\x01\
    \x02\0\x05\x12\x03\x13\x02\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x13\
    \t\x0e\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x13\x11\x12b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
